/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

export enum RdsIconId {
  AccountCircle = 'account-circle',
  AccountCircleFilled = 'account-circle-filled',
  AccountTree = 'account-tree',
  Add = 'add',
  AltRoute = 'alt-route',
  Apps = 'apps',
  Archive = 'archive',
  ArrowDownwardAlt = 'arrow-downward-alt',
  Badge = 'badge',
  Bolt = 'bolt',
  BrandAwareness = 'brand-awareness',
  Build = 'build',
  CalendarMonth = 'calendar-month',
  Cancel = 'cancel',
  Category = 'category',
  CenterFocusStrong = 'center-focus-strong',
  Close = 'close',
  Compare = 'compare',
  ContentCopy = 'content-copy',
  ContentPaste = 'content-paste',
  Crown = 'crown',
  CrownFilled = 'crown-filled',
  Database = 'database',
  Delete = 'delete',
  Description = 'description',
  Done = 'done',
  Download = 'download',
  Downloading = 'downloading',
  DragIndicator = 'drag-indicator',
  Edit = 'edit',
  FilterCenterFocus = 'filter-center-focus',
  FilterList = 'filter-list',
  Folder = 'folder',
  FolderOpen = 'folder-open',
  FormatListBulleted = 'format-list-bulleted',
  Fullscreen = 'fullscreen',
  GridView = 'grid-view',
  Groups = 'groups',
  GroupWork = 'group-work',
  Help = 'help',
  History = 'history',
  Home = 'home',
  HorizontalRule = 'horizontal-rule',
  Hourglass = 'hourglass',
  ImportContacts = 'import-contacts',
  Info = 'info',
  InkEraser = 'ink-eraser',
  KeepOff = 'keep-off',
  KeyboardArrowDown = 'keyboard-arrow-down',
  KeyboardArrowLeft = 'keyboard-arrow-left',
  KeyboardArrowRight = 'keyboard-arrow-right',
  KeyboardArrowUp = 'keyboard-arrow-up',
  KeyboardDoubleArrowLeft = 'keyboard-double-arrow-left',
  KeyboardDoubleArrowRight = 'keyboard-double-arrow-right',
  Link = 'link',
  LinkOff = 'link-off',
  Lock = 'lock',
  LockFilled = 'lock-filled',
  LockOpenRight = 'lock-open-right',
  Login = 'login',
  Logout = 'logout',
  ManageAccounts = 'manage-accounts',
  MoreHoriz = 'more-horiz',
  MoreVert = 'more-vert',
  NewReleases = 'new-releases',
  OpenInFull = 'open-in-full',
  OpenInNew = 'open-in-new',
  Palette = 'palette',
  Person = 'person',
  PersonFilled = 'person-filled',
  PlayArrow = 'play-arrow',
  PlayCircle = 'play-circle',
  PlaylistAdd = 'playlist-add',
  PlaylistAddCheck = 'playlist-add-check',
  PublishedWithChanges = 'published-with-changes',
  PushPin = 'push-pin',
  ReceiptLong = 'receipt-long',
  Refresh = 'refresh',
  Report = 'report',
  RocketLaunch = 'rocket-launch',
  Save = 'save',
  Schedule = 'schedule',
  Search = 'search',
  Sell = 'sell',
  Sell2 = 'sell-2',
  Send = 'send',
  Settings = 'settings',
  Sort = 'sort',
  SpellCheck = 'spellcheck',
  Star = 'star',
  StarFilled = 'star-filled',
  StarOff = 'star-off',
  Storefront = 'storefront',
  SubdirectoryArrowRight = 'subdirectory-arrow-right',
  Sync = 'sync',
  SyncAlt = 'sync-alt',
  SyncProblem = 'sync-problem',
  Tune = 'tune',
  Unarchive = 'unarchive',
  Upload = 'upload',
  Visibility = 'visibility',
  Warning = 'warning',
  WarningFilled = 'warning-filled',
  Weight = 'weight',
  Width = 'width',
}
export type IconToggle = [RdsIconId, RdsIconId];

export const rdsFavoriteIcon: Record<string, IconToggle> = {
  star: [RdsIconId.Star, RdsIconId.StarFilled],
} as const;
